# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/telemetry.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'proto/telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/telemetry.proto\x12\ttelemetry\"j\n\x07Reading\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12*\n\x0bsensor_type\x18\x02 \x01(\x0e\x32\x15.telemetry.SensorType\x12\r\n\x05value\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"e\n\x12SensorRegistration\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12*\n\x0bsensor_type\x18\x02 \x01(\x0e\x32\x15.telemetry.SensorType\x12\x10\n\x08location\x18\x03 \x01(\t*V\n\nSensorType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0bTEMPERATURE\x10\x01\x12\x0c\n\x08HUMIDITY\x10\x02\x12\x11\n\rSOIL_MOISTURE\x10\x03\x12\t\n\x05LIGHT\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORTYPE']._serialized_start=247
  _globals['_SENSORTYPE']._serialized_end=333
  _globals['_READING']._serialized_start=36
  _globals['_READING']._serialized_end=142
  _globals['_SENSORREGISTRATION']._serialized_start=144
  _globals['_SENSORREGISTRATION']._serialized_end=245
# @@protoc_insertion_point(module_scope)
